#!/usr/bin/env bash
# =============================================================================
# WoOdoo — Key Generator
# Generates cryptographically secure SECRET_KEY and FERNET_KEY
# Usage: bash scripts/generate-keys.sh
#        bash scripts/generate-keys.sh >> .env
# =============================================================================

set -euo pipefail

echo "# Generated by scripts/generate-keys.sh on $(date)"
echo ""

# Generate a 32-byte (64 hex char) random secret key for JWT signing
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
echo "SECRET_KEY=${SECRET_KEY}"

# Generate a Fernet encryption key for credential storage
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
echo "FERNET_KEY=${FERNET_KEY}"

echo ""
echo "# Copy the lines above into your .env file" >&2
